[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
minifb = "0.24.0"
glam = "0.23.0"
gltf = "1.0.0"
stb_image = "0.2.4"
